services:
  movie-db:
    build: 
      target: development
    ports:
      - "8080:8080"
    volumes:
      - ./movieDb-app/src:/app/movieDb-app/src
      - ./movieDb-app/dist:/app/movieDb-app/dist
      - ./movieDb-backend-src:/app/movieDb-backend-src
      - ./package.json:/app/package.json
      - ./.env:/app/.env
      - /app/node_modules
      - /app/movieDb-app/node_modules
    env_file: ./.env
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    networks:
      - moviedb-network

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    networks:
      - moviedb-network

networks:
  moviedb-network:
    name: moviedb-network
    driver: bridge